[package]
name = "nasomail_client"
version = "0.1.0"
authors = ["Anatnaso"]
edition = "2024"

[dependencies]
nasomail_shared = { path = "../nasomail_shared" }

dioxus = { version = "0.7.1", features = [] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
